# base
spring:
  datasource: 
    carhaha: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/carhaha?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 1234
    
#introPage (지금은 find my car로 바로 이동)
  webservice:
    intro: /fmc/main.do
